### ISSUE TITLE
Is it possible to edit the snippets? (Make the method opening curly brace to be on separate line)

### ISSUE THREAD

**Issue by 4unkur** [phiter/phpstorm-snippets-for-vscode#3]
As per PSR 12 the opening curly brace should go on its own line. How can I change the snippet to comply this rule?

**Comment by phiter** [comment]
Hi @4unkur , thank you for opening this issue. I haven't been working with PHP for a while now so I'm not aware of these changes.

But if you can open a MR I'd be glad to review and merge it, and then publish a new version.

This is the snippets file: https://github.com/phiter/phpstorm-snippets-for-vscode/blob/master/snippets/snippets.json

The edits should look like this:

```
        "body" : [
            "private function $1($2){",
            "\t$0",
            "}"
        ],
```

```
        "body" : [
            "private function $1($2)",
            "{"
            "\t$0",
            "}"
        ],
```

Each item in this array is a new line.
